import type { Locale } from './types';

type DynamicRule = {
  pattern: RegExp;
  format: (...matches: string[]) => string;
};

const exactEnglish: Record<string, string> = {
  '账号或密码不正确': 'Incorrect account or password',
  'LinZight 登录': 'LinZight login',
  '真实世界研究工作台': 'Real-world study workspace',
  '登录后进入患者队列、CRF 录入、样本登记、多组学检测、Patient Journey 与数据分析主链路。':
    'Sign in to access patient cohorts, CRF entry, sample registration, multi-omics testing, Patient Journey, and analytics workflows.',
  '主链路': 'Primary workflow',
  '登录': 'Login',
  '患者列表': 'Patient list',
  '样本': 'Samples',
  '组学': 'Omics',
  '上传': 'Upload',
  '分析': 'Analytics',
  '导出': 'Export',
  '账号登录': 'Account login',
  '开发阶段 Demo 认证': 'Demo authentication',
  '角色账号': 'Role account',
  '密码': 'Password',
  '登录中': 'Signing in',
  '进入系统': 'Enter system',

  '主导航': 'Main navigation',
  '首页工作台': 'Home',
  '患者队列管理': 'Patient Cohort',
  '知情同意': 'Informed Consent',
  '临床数据采集': 'Clinical Data Capture',
  '样本及检测': 'Samples & Testing',
  '患者旅程': 'Patient Journey',
  '数据分析': 'Analytics',
  '系统管理': 'System Admin',
  '主要研究者': 'Principal Investigator',
  '系统管理员': 'System Administrator',
  '项目管理员': 'Project Administrator',
  'PI研究者': 'PI Investigator',
  '数据管理员': 'Data Manager',
  '只读访客': 'Read-only Visitor',
  '研究助理 / CRC': 'Research Assistant / CRC',
  '研究医生 / PI': 'Research Doctor / PI',
  '当前角色': 'Current role',
  '当前角色：PI研究者': 'Current role: PI Investigator',
  '研究编号': 'Study ID',
  '研究编号：LGL-1111': 'Study ID: LGL-1111',
  '通知': 'Notifications',
  '退出登录': 'Sign out',
  '询问 LinZight AI': 'Ask LinZight AI',
  '询问 LinZight AI，例如：“查看本季度患者入组趋势”': 'Ask LinZight AI, for example: "Show this quarter enrollment trend"',
  '发送提示词': 'Send prompt',
  'AI 提示示例': 'AI prompt examples',
  '查看数据完整性': 'View data completeness',

  '欢迎回来，约翰·伦格博士': 'Welcome back, Dr. John Lenger',
  '这里是今日临床研究运营概览。': "Here is today's clinical study operations overview.",
  '管理和审核 LGL-1111 研究患者队列。': 'Manage and review the LGL-1111 study patient cohort.',
  '知情同意管理': 'Informed Consent Management',
  '管理患者授权、版本签署与审计轨迹。': 'Manage patient authorization, version signing, and audit trails.',
  '采集和审核 LGL-1111 研究结构化临床数据。': 'Capture and review structured clinical data for LGL-1111.',
  '管理样本采集、检测项目、结果文件和检测进度。': 'Manage sample collection, tests, result files, and testing progress.',
  '查看单患者从筛选、知情同意、临床随访到样本检测的全景数据。':
    'View the complete single-patient journey from screening and consent to follow-up and sample testing.',
  '导出 / 报表': 'Exports / Reports',
  '生成研究数据集、患者全景报表与审计导出。': 'Generate study datasets, patient panorama reports, and audit exports.',
  '管理账户、角色、字段配置和权限策略。': 'Manage accounts, roles, field configuration, and permission policies.',
  '搜索患者、住院号、疾病类型，或询问 LinZight AI...': 'Search patient, hospital number, disease type, or ask LinZight AI...',
  '询问 LinZight AI... 例如：列出待签署患者、汇总撤回情况':
    'Ask LinZight AI... For example: list patients pending signature or summarize withdrawals',
  '询问样本采集、检测状态、结果文件或患者样本情况...': 'Ask about sample collection, testing status, result files, or patient samples...',
  '询问单患者病程、样本结果、下次随访风险...': 'Ask about patient timeline, sample results, or next follow-up risk...',
  '询问报表生成、数据导出、SDTM 草稿或审计记录...': 'Ask about reports, data export, SDTM drafts, or audit records...',
  '询问角色权限、字段配置或系统审计...': 'Ask about role permissions, field configuration, or system audits...',

  '研究关键指标': 'Study key metrics',
  '看板可视化': 'Dashboard visualization',
  '运营概览': 'Operations overview',
  '当前模块': 'Current module',
  '已入组患者': 'Enrolled patients',
  '样本统计': 'Sample statistics',
  '随访次数': 'Follow-up visits',
  '临床数据完整性': 'Clinical data completeness',
  '来自 patients 表': 'From patients table',
  '来自 samples 表': 'From samples table',
  '来自 visits 表': 'From visits table',
  'clinical_data 平均值': 'clinical_data average',
  '已归档': 'archived',
  '来自 FastAPI / SQLite': 'From FastAPI / SQLite',
  '已识别': 'Identified',
  '已筛选': 'Screened',
  '已入组': 'Enrolled',
  '治疗中': 'On treatment',
  '随访中': 'In follow-up',
  '已完成': 'Completed',
  '患者总数': 'Total patients',
  '唯一患者': 'Unique patients',
  '中位年龄': 'Median age',
  '女性占比': 'Female ratio',
  '平均合并症': 'Average comorbidities',
  '中位随访': 'Median follow-up',
  '患者筛选': 'Patient screening',
  '基线访视': 'Baseline visit',
  '样本采集': 'Sample collection',
  '随访访视': 'Follow-up visit',
  '数据锁库': 'Database lock',
  '已处理样本': 'Processed samples',
  '检测归档率': 'Testing archive rate',
  '检测项目': 'Testing items',
  'SLA 达标率': 'SLA attainment',
  'SLA 目标': 'SLA target',
  '智能摘要': 'Smart summary',
  'LinZight AI 生成': 'Generated by LinZight AI',
  '查看全部洞察 →': 'View all insights ->',
  '工作流进度': 'Workflow progress',
  '工作流研究筛选': 'Workflow study filter',
  '全部研究': 'All studies',
  '总体': 'Overall',
  '进度': 'Progress',
  '入组趋势': 'Enrollment trend',
  '入组时间范围': 'Enrollment time range',
  '本季度': 'This quarter',
  '入组趋势图': 'Enrollment trend chart',
  '累计入组': 'Cumulative enrollment',
  '较上季度 18.6%': '18.6% vs last quarter',
  '多组学检测的统计': 'Multi-omics testing statistics',
  '多组学时间范围': 'Multi-omics time range',
  '本月': 'This month',
  '查看实验室看板 →': 'View lab dashboard ->',
  '中位 TAT': 'Median TAT',
  '实时统计': 'Real-time stats',
  '患者旅程概览': 'Patient journey overview',
  '查看全部患者 →': 'View all patients ->',
  '真实世界队列概览': 'Real-world cohort overview',
  '查看队列分析 →': 'View cohort analytics ->',
  'CRF 录入': 'CRF entry',
  '组学归档': 'Omics archive',
  '更多快捷操作': 'More quick actions',
  '入组趋势较上一季度提升 18.6%。': 'Enrollment trend improved by 18.6% vs last quarter.',
  '入组趋势较上一季度提升 ': 'Enrollment trend improved by ',
  '7 号中心和 12 号中心入组增长领先。': 'Sites 7 and 12 lead enrollment growth.',
  '7 号中心': 'Site 7',
  '12 号中心': 'Site 12',
  '和 ': ' and ',
  '入组增长领先。': ' lead enrollment growth.',
  '受 ePRO 推动，数据完整性提升 3.4%。': 'Driven by ePRO, data completeness improved by 3.4%.',
  '受 ePRO 推动，数据完整性提升 ': 'Driven by ePRO, data completeness improved by ',
  '12 名患者存在错过下次访视风险。': '12 patients are at risk of missing the next visit.',
  '12 名患者': '12 patients',
  '存在错过下次访视风险。': ' are at risk of missing the next visit.',
  '。': '.',

  '患者队列关键指标': 'Patient cohort key metrics',
  '队列概览': 'Cohort overview',
  '总计': 'Total',
  '数据完整性趋势': 'Data completeness trend',
  '当前': 'Current',
  '样本采集汇总': 'Sample collection summary',
  '患者编号': 'Patient ID',
  '住院号': 'Hospital No.',
  '性别': 'Sex',
  '年龄': 'Age',
  '疾病类型': 'Disease type',
  '受累脏器': 'Affected organs',
  '多组学检测': 'Multi-omics testing',
  '完整性': 'Completeness',
  '注释': 'Notes',
  '操作': 'Actions',
  '查看': 'View',
  '编辑': 'Edit',
  '暂无匹配患者': 'No matching patients',
  '按患者、样本和组学进度筛选队列': 'Filter cohorts by patient, sample, and omics progress',
  '新建患者': 'New patient',
  '患者搜索': 'Patient search',
  '输入患者编号、住院号或疾病类型': 'Enter patient ID, hospital number, or disease type',
  '年龄范围': 'Age range',
  '排序': 'Sort',
  '上一页': 'Previous page',
  '下一页': 'Next page',
  '患者队列筛选': 'Patient cohort filters',
  '女性': 'Female',
  '样本已采集': 'Samples collected',
  '完整性 >80%': 'Completeness >80%',
  '数据源：数据库实时同步': 'Source: real-time database sync',
  '数据库实时': 'Live database',
  '占总数': 'Of total',
  '平均完整度': 'Average completeness',
  '最近更新': 'Latest update',
  '完整性优先': 'Completeness first',
  '年龄升序': 'Age ascending',
  '全部': 'All',
  '男': 'Male',
  '女': 'Female',
  '血液': 'Blood',
  '脑脊液': 'CSF',
  '肾': 'Kidney',
  '总样本数': 'Total samples',
  '完成': 'Complete',
  '进行中': 'In progress',
  '结果归档': 'Result archived',

  '快捷操作': 'Quick actions',
  '新增患者': 'Add patient',
  '数据录入': 'Data entry',
  '样本录入': 'Sample entry',
  '随访录入': 'Follow-up entry',

  'Account Summary | 账户概览': 'Account Summary',
  '当前研究站点账户结构': 'Current study site account structure',
  'Create Account新增账户': 'Create Account',
  '账户创建、权限策略变更均进入审计日志。': 'Account creation and permission policy changes are recorded in the audit log.',
  'User Accounts & Roles List | 用户账户与角色列表': 'User Accounts & Roles List',
  '按角色和状态管理研究团队账号': 'Manage study team accounts by role and status',
  'Field & CRF Configuration | CRF 与字段配置': 'Field & CRF Configuration',
  '维护结构化 CRF 字段、类型和所属模块': 'Maintain structured CRF fields, types, and modules',
  '新增字段': 'Add field',
  'Permission Strategy Matrix | 权限策略矩阵': 'Permission Strategy Matrix',
  '按角色定义患者、样本、组学、导入与系统配置权限': 'Define patient, sample, omics, import, and system permissions by role',
  'Research Doctor / PI研究医生 / PI': 'Research Doctor / PI',
  'CRC / Research AssistantCRC / 研究助理': 'CRC / Research Assistant',
  'System Administrator系统管理员': 'System Administrator',

  '等待导出任务': 'Waiting for export task',
  '等待数据校验': 'Waiting for data validation',
  '导出失败：请确认已登录且当前角色具备导出权限': 'Export failed: confirm login and export permission',
  '数据校验运行中...': 'Data validation running...',
  '校验失败：请确认当前角色具备质控权限': 'Validation failed: confirm quality control permission',
  '可导出报表': 'Exportable reports',
  '数据库记录': 'Database records',
  '审计轨迹': 'Audit trail',
  '待复核': 'Pending review',
  '患者、样本、组学检测': 'Patients, samples, omics tests',
  '含知情同意与数据修改': 'Includes consent and data changes',
  'SDTM 数据集草稿': 'SDTM dataset draft',
  '数据导出流水线': 'Data export pipeline',
  '用于 Demo 后端 API 联调': 'For demo backend API integration',
  '运行校验': 'Run validation',
  '患者主数据': 'Patient master data',
  '临床 CRF': 'Clinical CRF',
  '样本台账': 'Sample ledger',
  '多组学结果': 'Multi-omics results',
  '知情同意审计': 'Consent audit',
  '数据包归档': 'Data package archive',
  '可导出': 'Exportable',
  '格式': 'Format',
  '状态': 'Status',
  '更新时间': 'Updated at',

  '已签署': 'Signed',
  '待签署': 'Pending signature',
  '已撤回': 'Withdrawn',
  '电子': 'Electronic',
  '纸质': 'Paper',
  '已采集': 'Collected',
  '已送检': 'Sent for testing',
  '检测中': 'Testing',
  '检测完成': 'Testing complete',
  '结果回传': 'Results returned',
  '待处理': 'Pending',
  '通过': 'Passed',
  '未通过': 'Failed',
  '待确认': 'Pending confirmation',
  '样本接收': 'Sample received',
  '文库构建': 'Library prep',
  '测序完成': 'Sequencing complete',
  '已预约': 'Scheduled',
  '生成中': 'Generating',
  '需复核': 'Needs review',
  '启用': 'Enabled',
  '草稿': 'Draft',

  '基本信息': 'Basic info',
  '随访日期': 'Follow-up date',
  '多次随访': 'Repeated follow-up',
  '标志物结果': 'Biomarker result',
  '实验室结果': 'Lab results',
  '结果文件': 'Result file',
  '字段配置': 'Field configuration',
  '权限策略管理': 'Permission policy'
};

const phraseEnglish = ([
  ['真实世界研究', 'real-world study'],
  ['真实世界队列', 'real-world cohort'],
  ['患者队列', 'patient cohort'],
  ['知情同意', 'informed consent'],
  ['临床数据采集', 'clinical data capture'],
  ['样本及检测', 'samples and testing'],
  ['患者旅程', 'patient journey'],
  ['数据分析', 'analytics'],
  ['系统管理', 'system admin'],
  ['多组学检测', 'multi-omics testing'],
  ['多组学', 'multi-omics'],
  ['患者', 'patient'],
  ['样本', 'sample'],
  ['检测', 'testing'],
  ['随访', 'follow-up'],
  ['下次', 'next'],
  ['访视', 'visit'],
  ['入组', 'enrollment'],
  ['趋势', 'trend'],
  ['增长', 'growth'],
  ['上一季度', 'last quarter'],
  ['提升', 'improved'],
  ['中心', 'site'],
  ['领先', 'lead'],
  ['风险', 'risk'],
  ['错过', 'missing'],
  ['研究', 'study'],
  ['队列', 'cohort'],
  ['数据', 'data'],
  ['完整性', 'completeness'],
  ['审计', 'audit'],
  ['报表', 'report'],
  ['导出', 'export'],
  ['角色', 'role'],
  ['账户', 'account'],
  ['权限', 'permission'],
  ['字段', 'field'],
  ['配置', 'configuration'],
  ['状态', 'status'],
  ['更新时间', 'updated at'],
  ['总计', 'total'],
  ['当前', 'current'],
  ['全部', 'all'],
  ['新增', 'add'],
  ['查看', 'view'],
  ['编辑', 'edit'],
  ['运行', 'run'],
  ['校验', 'validation'],
  ['完成', 'complete'],
  ['待复核', 'pending review'],
  ['进行中', 'in progress'],
  ['已归档', 'archived'],
  ['已签署', 'signed'],
  ['待签署', 'pending signature'],
  ['已撤回', 'withdrawn'],
  ['数据库', 'database'],
  ['实时', 'real-time'],
  ['搜索', 'search'],
  ['筛选', 'filter'],
  ['排序', 'sort'],
  ['密码', 'password'],
  ['登录', 'login'],
  ['退出', 'sign out'],
  ['通知', 'notifications'],
  ['女', 'female'],
  ['男', 'male'],
  ['血液', 'blood'],
  ['脑脊液', 'CSF'],
  ['肾组织', 'kidney tissue'],
  ['肾', 'kidney'],
  ['尿液', 'urine'],
  ['皮肤组织', 'skin tissue'],
  ['唾液腺组织', 'salivary gland tissue'],
  ['脊髓组织', 'spinal cord tissue'],
  ['淋巴结组织', 'lymph node tissue'],
  ['视神经相关组织', 'optic nerve-related tissue'],
  ['周围神经组织', 'peripheral nerve tissue'],
  ['肌肉组织', 'muscle tissue'],
  ['粪便', 'stool'],
  ['口腔', 'buccal swab'],
  ['鼻咽', 'nasopharyngeal swab'],
  ['脑组织', 'brain tissue'],
  ['天', 'days'],
  ['月', 'months'],
  ['岁', 'years']
] as Array<[string, string]>).sort((a, b) => b[0].length - a[0].length);

const dynamicRules: DynamicRule[] = [
  {
    pattern: /^显示 (\d+) 至 (\d+) 条，共 (\d+) 条记录$/,
    format: (start, end, total) => `Showing ${start}-${end} of ${total} records`
  },
  {
    pattern: /^已定位患者：(.+) \/ 住院号 (.+)$/,
    format: (patient, hospitalNo) => `Selected patient: ${patient} / Hospital No. ${hospitalNo}`
  },
  {
    pattern: /^(.+) 生成中\.\.\.$/,
    format: (name) => `${translateToEnglish(name)} generating...`
  },
  {
    pattern: /^(.+) 已生成：(.+)$/,
    format: (name, id) => `${translateToEnglish(name)} generated: ${id}`
  },
  {
    pattern: /^校验完成：发现 (\d+) 条待处理问题$/,
    format: (count) => `Validation complete: ${count} pending issues found`
  },
  {
    pattern: /^(.+) 项已归档$/,
    format: (count) => `${count} archived`
  },
  {
    pattern: /^(.+)例$/,
    format: (count) => `${count} cases`
  },
  {
    pattern: /^较近 (\d+) 天$/,
    format: (days) => `Last ${days} days`
  },
  {
    pattern: /^V(\d+) 基线访视$/,
    format: (visit) => `V${visit} baseline visit`
  },
  {
    pattern: /^V(\d+) (\d+)月随访$/,
    format: (visit, month) => `V${visit} ${month}-month follow-up`
  },
  {
    pattern: /^(\d+)月$/,
    format: (month) => `${month}M`
  }
];

function preserveOuterWhitespace(source: string, translated: string) {
  const leading = source.match(/^\s*/)?.[0] ?? '';
  const trailing = source.match(/\s*$/)?.[0] ?? '';
  return `${leading}${translated}${trailing}`;
}

function normalizeBilingualBreaks(text: string) {
  return text
    .replace(/\s*\|\s*/g, ' | ')
    .replace(/([a-z])([A-Z])/g, '$1 $2')
    .replace(/([a-zA-Z])([\u4e00-\u9fa5])/g, '$1 $2')
    .replace(/([\u4e00-\u9fa5])([a-zA-Z])/g, '$1 $2');
}

export function translateToEnglish(source: string): string {
  const trimmed = source.trim();
  if (!trimmed) return source;

  const exact = exactEnglish[trimmed];
  if (exact) return preserveOuterWhitespace(source, exact);

  for (const rule of dynamicRules) {
    const match = trimmed.match(rule.pattern);
    if (match) return preserveOuterWhitespace(source, rule.format(...match.slice(1)));
  }

  let translated = normalizeBilingualBreaks(trimmed);
  for (const [zh, en] of phraseEnglish) {
    translated = translated.split(zh).join(en);
  }

  return preserveOuterWhitespace(source, translated);
}

export function translateText(source: string, locale: Locale) {
  if (locale === 'zh-CN') return source;
  return translateToEnglish(source);
}
